/**
 * This file was automatically generated by Supabase.
 * Do not edit it manually.
 */

export interface Database {
  public: {
    Tables: {
      guest_lists: {
        Row: {
          id: string
          created_at: string
          original_filename: string
          s3_key: string
          event_date: string
          share_token: string
          status: 'draft' | 'ready'
        }
        Insert: {
          id?: string
          created_at?: string
          original_filename: string
          s3_key: string
          event_date: string
          share_token: string
          status?: 'draft' | 'ready'
        }
        Update: {
          id?: string
          created_at?: string
          original_filename?: string
          s3_key?: string
          event_date?: string
          share_token?: string
          status?: 'draft' | 'ready'
        }
      }
      guests: {
        Row: {
          id: string
          guest_list_id: string
          first_name: string
          last_name: string | null
          email: string | null
          num_tickets: number
          notes: string | null
        }
        Insert: {
          id?: string
          guest_list_id: string
          first_name: string
          last_name?: string | null
          email?: string | null
          num_tickets?: number
          notes?: string | null
        }
        Update: {
          id?: string
          guest_list_id?: string
          first_name?: string
          last_name?: string | null
          email?: string | null
          num_tickets?: number
          notes?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
} 